"""tabela sites

Revision ID: 10931362cbb6
Revises: d4280d5f1202
Create Date: 2020-08-13 19:38:29.115904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10931362cbb6'
down_revision = 'd4280d5f1202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grau', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=45), nullable=True),
    sa.Column('tribunal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tribunal_id'], ['tribunal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site')
    # ### end Alembic commands ###
