"""update_tabela_processo

Revision ID: f76826cb7a59
Revises: 10931362cbb6
Create Date: 2020-08-16 18:34:26.655378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76826cb7a59'
down_revision = '10931362cbb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processo', sa.Column('area', sa.String(length=30), nullable=True))
    op.add_column('processo', sa.Column('assunto', sa.String(length=30), nullable=True))
    op.add_column('processo', sa.Column('classe', sa.String(length=50), nullable=True))
    op.add_column('processo', sa.Column('distribuição', sa.String(length=100), nullable=True))
    op.add_column('processo', sa.Column('valor_acao', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processo', 'valor_acao')
    op.drop_column('processo', 'distribuição')
    op.drop_column('processo', 'classe')
    op.drop_column('processo', 'assunto')
    op.drop_column('processo', 'area')
    # ### end Alembic commands ###
