"""correcao na tabela de processos

Revision ID: febf3c0c1755
Revises: f76826cb7a59
Create Date: 2020-08-27 15:57:10.018494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'febf3c0c1755'
down_revision = 'f76826cb7a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processo', sa.Column('distribuicao', sa.String(length=100), nullable=True))
    op.drop_column('processo', 'distribuição')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processo', sa.Column('distribuição', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('processo', 'distribuicao')
    # ### end Alembic commands ###
